### ISSUE TITLE
Feature request: Add a keyboardist

### ISSUE THREAD

**Issue by szymon-rd** [kgadek/paintdrops-co#1]
This product could benefit from a feature of a keyboardist, also known as a musician specializing in the keyboard.

Reference:
https://www.oxfordlearnersdictionaries.com/definition/english/keyboardist

**Comment by kgadek** [comment]
Send a CV and we may consider. Rn we're not looking for expansion of the band, but who knows.

Nevertheless, let's keep this repo for issues related to website.
